### ISSUE TITLE
Error parsing STM32F103 SVD

### ISSUE THREAD

**Issue by nshp** [ehntoo/binaryninja-svd#5] opened 2020-10-01 15:55 UTC
```Traceback (most recent call last):
  File "/opt/binaryninja/plugins/../python/binaryninja/plugin.py", line 144, in _default_action
    action(view_obj)
  File "/home/nick/.binaryninja/repositories/community/plugins/ehntoo_binaryninjasvd/__init__.py", line 7, in load_svd
    device = parse(svd_file)
  File "/home/nick/.binaryninja/repositories/community/plugins/ehntoo_binaryninjasvd/svdmmap.py", line 168, in parse
    tree = ET.parse(svdfile)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

From loading https://stm32-rs.github.io/stm32-rs/stm32f103.svd.patched

**Comment by ehntoo** [comment] 2020-10-02 12:12
Huh. I've used previous versions of the f103 SVD without issue - I'll try and triage tonight. Thanks for the report!

**Comment by ehntoo** [comment] 2020-10-02 13:16
Gave this a shot and didn't have any issues with that SVD. Could you provide some platform details? From the stack trace you've given it looks like the file chooser failed to return a path.

Perhaps you hit "cancel" instead of open in the file chooser? I should probably handle that case cleanly rather than passing the resulting None down to the parse method.

**Comment by psifertex** [comment] 2020-10-02 15:05
Don't worry about the none case, that's also coming with the browser PR. 😛

**Comment by ehntoo** [comment] 2021-12-30 21:11
Closing due to lack of reproducibility.

**Closed by ehntoo** 2021-12-30 21:11 UTC
Labels: needsinfo
